---
- name: Specify the initial username and password
  xy8000.uptime_kuma.setup:
    api_url: "http://127.0.0.1:{{ web_ui_port }}"
    api_username: "{{ kuma_username }}"
    api_password: "{{ kuma_password }}"
- name: Add Monitors
  xy8000.uptime_kuma.monitor:
    api_url: "http://127.0.0.1:{{ web_ui_port }}"
    api_username: "{{ kuma_username }}"
    api_password: "{{ kuma_password }}"
    name: "{{ item.name }}"
    url: "{{ item.url }}"
    type: "{{ item.type }}"
    state: present
  loop: "{{ kuma_monitors }}"