---
- include_tasks: print-vars.yaml
- include_tasks: configure-python.yaml
- include_tasks: configure-ufw.yaml
  when: configure_ufw
- include_tasks: install-kuma.yaml
- include_tasks: configure-kuma.yaml